### ISSUE TITLE
Add feedstock's `catalog.yaml` and `meta.yaml` validation via GitHub actions

### ISSUE THREAD

**Issue by andersy005** [leap-stc/LEAP_template_feedstock#41]
i just finished creating a GitHub Action to validate the catalog.yaml in feedstocks. the action is located in the `leap-stc/data-catalog-actions` repository. below is an example workflow that can be used to enable this action in the repository.

`.github/workflows/validate-catalog.yaml`

```yaml
name: catalog

on:
  pull_request:
    branches:
  push:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    validate:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: validate feedstock entry
              uses: leap-stc/data-catalog-actions/leap-catalog@main
              with:
                single-feedstock: "./feedstock/catalog.yaml"
```

@norlandrhagen / @jbusecke, do you mind adding this to the following repos ( i don;t have write privileges)

- [x] https://github.com/leap-stc/aws-noaa-oisst-pangeo-forge-feedstock
- [x] https://github.com/leap-stc/cesm-atm-025deg-pangeo-forge-osn-feedstock
- [x] https://github.com/leap-stc/large-ensemble-pCO2-testbed-feedstock
- [x] https://github.com/leap-stc/EOBS-pangeo-forge-osn-feedstock
- [x] https://github.com/leap-stc/NOAA-Coastwatch-Geo-Polar-SST-pangeo-forge-osn-feedstock
- [x] https://github.com/leap-stc/LMRv2.1-Monte-Carlo-Gridded-pangeo-forge-osn-feedstock
- [x] https://github.com/leap-stc/evolv2k-vssi-database-pangeo-forge-osn-feedstock
- [x] https://github.com/leap-stc/metaflux_feedstock
